name: "hapro (Development)"
description: "Development version, don't use except when instructed to do so. Professional manager for multiple HA installations."
slug: "hapro-dev"
version: "v1.0.1"
image: ghcr.io/bitfox-git/hapro-dev-addon-{arch}
url: "https://github.com/bitfox-git/hapro-addon/tree/main/hapro-dev"
init: false
host_network: true
homeassistant_api: true
hassio_api: true
hassio_role: "manager"
arch:
  - aarch64
  - amd64
map:
  - homeassistant_config:rw
  - backup:rw
options:
  uuid: "Your UUID has not been identified yet, it will be fetched by the addon."
schema:
  uuid: str?
