blueprint:
  name: HaPro Notification Blueprint - v1.1
  description: Get notified by the hapro system on selected triggers
  domain: automation
  author: Melchior - Ludero
  input:
    cooldown:
      name: Cooldown
      description: The amount of seconds until the notification can be triggered again
      default: 120
      selector:
        number:
          min: 30
          max: 6000
          unit_of_measurement: seconds
          mode: slider
    triggers:
      name: Triggers
      description: Here you can define any triggers to send a notification, fe. when current_production_power < 100W
      selector:
        trigger:
    title:
      name: Title
      description: The Title for the notification, fe. Low Power Production. The prefix SUBDOMAIN will be replaced by the subdomain of your homeassistant
      selector:
        text:
          prefix: "SUBDOMAIN"
          type: text
    description:
      name: Description
      description: "A more detailed description of the notification, fe. Your current power production has dropped below the configured threshold of: 100W"
      selector:
        text:
          type: text
    urgency:
      name: Urgency
      description: "The urgency of the notification"
      selector:
        select:
          options:
            - Critical
            - Warning
            - Info

mode: restart
max_exceeded: silent

triggers: !input triggers
variables:
  cooldown: !input cooldown
  title: !input title
conditions:
  - condition: template
    value_template: >-
      {{ not state_attr(this.entity_id, 'last_triggered') or
      (as_timestamp(now()) -
      as_timestamp(state_attr(this.entity_id,'last_triggered'))) >
      cooldown }}

actions:
  - event: hapro_notification
    event_data:
      type: !input urgency
      title: "{{ title }}"
      message: !input description
      datetime: "{{ now().isoformat() }}"
