name: "hapro"
description: "Professional manager for multiple HA installations."
slug: "hapro"
version: "v1.2"
image: ghcr.io/ludero-git/hapro-addon-{arch}
url: "https://github.com/ludero-git/hapro-addon/tree/main/hapro"
init: false
host_network: true
homeassistant_api: true
hassio_api: true
hassio_role: "manager"
arch:
  - aarch64
  - amd64
map:
  - homeassistant_config:rw
  - backup:rw
options:
  uuid: "Your UUID has not been identified yet, it will be fetched by the addon."
  apiUrl: "https://api.ludero.nl"
  debug: false
schema:
  uuid: str?
  apiUrl: str
  debug: bool?
